# Generated by Django 5.1.4 on 2024-12-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='description',
            new_name='descriptionnn',
        ),
    ]
