# Generated by Django 5.1.4 on 2024-12-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_description_discount_descriptionnn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='descriptionnn',
            new_name='description',
        ),
    ]
