# Generated by Django 5.1.4 on 2024-12-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_customer_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UN', 'Unpaid'), ('P', 'Paid'), ('C', 'Canceled')], default='UN', max_length=10),
        ),
    ]
